my_tuple=(1,2,3,4)
print(my_tuple)
print(my_tuple[2])
print(my_tuple[0:3])
print(len(my_tuple))
my_tuple2=(5,6,7,8,)
print(max(my_tuple2))
print(min(my_tuple2))
print(sum(my_tuple2))
print(max(my_tuple2)/len(my_tuple2))
print( my_tuple2.index(7))
print(my_tuple.count(4))

my_tuple3=("v,jhope,jimin")
print(my_tuple3)
print(my_tuple3.index())
print(my_tuple3.count("jhope"))
